# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"
  #config.vm.box = "ubuntu/trusty64"
  config.vm.network :private_network, ip: "192.168.68.8"
  #
  # take too much time
  #for i in 2500..10000
  #  config.vm.network :forwarded_port, guest: i, host: i
  #end

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 8081, host: 8081
  config.vm.network :forwarded_port, guest: 8082, host: 8082
  config.vm.network :forwarded_port, guest: 8001, host: 8001
  config.vm.network :forwarded_port, guest: 9090, host: 9090
  config.vm.network :forwarded_port, guest: 16686, host: 16686

  config.vm.provider :virtualbox do |vb|
    vb.name = "fluentd"
    vb.memory = "8192"
    vb.cpus = "4"
  end

end
