# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"
#  config.vm.network "private_network", ip: "10.10.10.10"
#  config.vm.network "forwarded_port", guest: 8888, host: 9999, auto_correct: true
  config.vm.network "public_network"

  config.vm.provider :virtualbox do |vb|
    vb.name = "anna"
    vb.memory = "8192"
    vb.cpus = "4"
  end

end
