# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "10.55.55.102"

  config.vm.provider :virtualbox do |vb|
    vb.name = "Trusty2"
    vb.memory = "8192"
    vb.cpus = "4"
  end

end
