# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "public_network"

  config.vm.provider :virtualbox do |vb|
    vb.name = "minikube"
    vb.memory = "8192"
    vb.cpus = "4"
  end

end
