# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
#  config.vm.box = "box-cutter/ubuntu1404-desktop"
#  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
#  config.vm.network "forwarded_port", guest: 5901, host: 5901
#  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.provider "virtualbox" do |vb|
#    vb.gui = true
#    vb.customize ["modifyvm", :id, "--monitorcount", "2"]
    vb.memory = "8192"
  end
      
end

