# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  #config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :private_network, ip: "192.168.68.8"
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 8001, host: 8001

  config.vm.provider :virtualbox do |vb|
    vb.name = "anna3"
    vb.memory = "8192"
    vb.cpus = "4"
  end

end
