# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/xenial64"

  # Accessing "localhost:5000" will access port 5000 on the guest machine.
  config.vm.network :forwarded_port, guest: 5000, host: 5000

  # Private Network
  config.vm.network :private_network, ip: "192.168.68.8"

  config.vm.provider :virtualbox do |vb|
    vb.name = "digits"
    vb.memory = "8192"
    vb.cpus = "4"
  end

  # Install stuff
  # config.vm.provision :shell, :path => "./bootstrap.sh"
end
